elasticsearch:
  restart: on-failure:5
  image: bitergia/elasticsearch:6.1.0
  command: /elasticsearch/bin/elasticsearch -Enetwork.bind_host=0.0.0.0 -Ehttp.max_content_length=2000mb
  environment:
    - ES_JAVA_OPTS=-Xms2g -Xmx2g
  ulimits:
    nofile:
      soft: 65536
      hard: 65536
  ports:
    - "9200:9200"
  log_driver: "json-file"
  log_opt:
    max-size: "100m"
    max-file: "3"

kibiter:
  restart: on-failure:5
  image: bitergia/kibiter:optimized-v6.1.4-2
  environment:
    - PROJECT_NAME=TEST
    - NODE_OPTIONS=--max-old-space-size=1200
    - ELASTICSEARCH_URL=http://elasticsearch:9200
  links:
    - elasticsearch
  ports:
    - "5601:5601"
  log_driver: "json-file"
  log_opt:
    max-size: "100"

